### PR TITLE
Updated modules to load newer assemblies

### PR DESCRIPTION
**Pull request by PatrickKeisler**
I updated the Agent, Repl, and SSIS modules to load the newer assemblies. This should fix issue #13.

### CODE REVIEW

**Comment by MikeShepard** [comment]
I appreciate the work.  I'm trying to get back up to speed with a test box, but in the meantime it's really nice to have someone putting effort into the project.

There are a few problems with the code in terms of standards, should be pretty easy to fix:

Get-Errors   - Nouns should be singular (Get-Error)
                    - Should use a param statement with typed parameters

Get-CMSServers - Nouns should be singular

Parse-ServerGroup - should use a param statement
                                - Need to use an approved verb.

**Comment by PatrickKeisler** [comment]
Thanks. I've used SQLPSX in the past, so I thought it would be nice to
contribute to the project. I'll get some of those items corrected before I
issue another pull. I'm working on a new module (CMS) for central
management server so I can pull a list of servers to feed into
Get-SqlServer, etc.

Have a good July 4th weekend!

Patrick

**Comment by PatrickKeisler** [comment]
Btw, have you read this? There is now a module called SqlServer built-in to
SQL as of the July 2016 SSMS update.

https://blogs.technet.microsoft.com/dataplatforminsider/2016/06/30/sql-powershell-july-2016-update/

**Comment by MikeShepard** [comment]
Yes...I saw that.  It will cause some interesting name collisions.

On Tue, Jul 5, 2016 at 2:11 PM, Patrick Keisler notifications@github.com
wrote:

> Btw, have you read this? There is now a module called SqlServer built-in to
> SQL as of the July 2016 SSMS update.
> 
> https://blogs.technet.microsoft.com/dataplatforminsider/2016/06/30/sql-powershell-july-2016-update/
> 
> On Fri, Jul 1, 2016 at 11:18 AM, Patrick Keisler pkeisler@gmail.com
> wrote:
> 
> > Thanks. I've used SQLPSX in the past, so I thought it would be nice to
> > contribute to the project. I'll get some of those items corrected before
> > I
> > issue another pull. I'm working on a new module (CMS) for central
> > management server so I can pull a list of servers to feed into
> > Get-SqlServer, etc.
> > 
> > Have a good July 4th weekend!
> > 
> > Patrick
> > 
> > On Fri, Jul 1, 2016 at 11:10 AM, MikeShepard notifications@github.com
> > wrote:
> > 
> > > I appreciate the work. I'm trying to get back up to speed with a test
> > > box, but in the meantime it's really nice to have someone putting effort
> > > into the project.
> > > 
> > > There are a few problems with the code in terms of standards, should be
> > > pretty easy to fix:
> > > 
> > > Get-Errors - Nouns should be singular (Get-Error)
> > > - Should use a param statement with typed parameters
> > > 
> > > Get-CMSServers - Nouns should be singular
> > > 
> > > Parse-ServerGroup - should use a param statement
> > > 
> > > —
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly, view it on GitHub
> > > https://github.com/MikeShepard/SQLPSX/pull/14#issuecomment-229972018,
> > > or mute the thread
> > > <
> > > https://github.com/notifications/unsubscribe/AS3YbZoja7p3hUlPHfBe10gobMMFQsxyks5qRS3VgaJpZM4I_QTJ
> > > 
> > > .
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/MikeShepard/SQLPSX/pull/14#issuecomment-230573545,
> or mute the thread
> https://github.com/notifications/unsubscribe/AFSNIn3IPEEG00cSeh2ldU57AMpwSao_ks5qSqxTgaJpZM4I_QTJ
> .

## 

https://powershellstation.com

**Comment by PatrickKeisler** [comment]
There are only 2 at the moment as of the July 2016 update: Get-SqlDatabase & Get-SqlErrorLog.

**Comment by MikeShepard** [comment]
I was talking about the actual module name (SQLServer).

On Wed, Jul 6, 2016 at 8:25 AM, Patrick Keisler notifications@github.com
wrote:

> There are only 2 at the moment as of the July 2016 update: Get-SqlDatabase
> & Get-SqlErrorLog.
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> https://github.com/MikeShepard/SQLPSX/pull/14#issuecomment-230770054,
> or mute the thread
> https://github.com/notifications/unsubscribe/AFSNInbmUIEyG4ImJ805PDKRv2LKr1OUks5qS6y2gaJpZM4I_QTJ
> .

## 

https://powershellstation.com

**Pull request merged**
